//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dasmic.MLLib.Common.Exceptions.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dasmic.MLLib.Common.Exceptions.Resources.strings_messages", typeof(strings_messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of attributes in training data and attribute headers do not match.
        /// </summary>
        internal static string exception_attribute_mismatch {
            get {
                return ResourceManager.GetString("exception_attribute_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute count passed do not match the attribute count used for training the model.
        /// </summary>
        internal static string exception_attribute_mismatch_run_model {
            get {
                return ResourceManager.GetString("exception_attribute_mismatch_run_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stride value of the CNN is not valid.
        /// </summary>
        internal static string exception_cnn_stride_value {
            get {
                return ResourceManager.GetString("exception_cnn_stride_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of data columns do not match.
        /// </summary>
        internal static string exception_data_column_mismatch {
            get {
                return ResourceManager.GetString("exception_data_column_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range.
        /// </summary>
        internal static string exception_index_out_of_range {
            get {
                return ResourceManager.GetString("exception_index_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data passed is not valid.
        /// </summary>
        internal static string exception_invalid_data {
            get {
                return ResourceManager.GetString("exception_invalid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dataset file is not in a correct format.
        /// </summary>
        internal static string exception_invalid_data_set_file {
            get {
                return ResourceManager.GetString("exception_invalid_data_set_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is not valid.
        /// </summary>
        internal static string exception_invalid_matrix {
            get {
                return ResourceManager.GetString("exception_invalid_matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Neural Network Layer is Invalid. Check the layer index and verify if number of Layers has been intialized.
        /// </summary>
        internal static string exception_invalid_neural_net_layer {
            get {
                return ResourceManager.GetString("exception_invalid_neural_net_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters passed to the function are invalid.
        /// </summary>
        internal static string exception_invalid_parameters {
            get {
                return ResourceManager.GetString("exception_invalid_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The training data is not valid.
        /// </summary>
        internal static string exception_invalid_training_data {
            get {
                return ResourceManager.GetString("exception_invalid_training_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU decomposition of the matrix failed.
        /// </summary>
        internal static string exception_lu_decomposition {
            get {
                return ResourceManager.GetString("exception_lu_decomposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input matrices do not match to perform this operation.
        /// </summary>
        internal static string exception_matrix_input_mismatch {
            get {
                return ResourceManager.GetString("exception_matrix_input_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is not ready. Please train the model  and try again..
        /// </summary>
        internal static string exception_model_not_ready {
            get {
                return ResourceManager.GetString("exception_model_not_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem was encountered in running the model. Please check your input data..
        /// </summary>
        internal static string exception_model_run {
            get {
                return ResourceManager.GetString("exception_model_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Neural Network configuration is not ready. Please check if all layers have been added and configured correctly..
        /// </summary>
        internal static string exception_neural_net_configuration {
            get {
                return ResourceManager.GetString("exception_neural_net_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target index is not the last index in training data.
        /// </summary>
        internal static string exception_target_index_not_last {
            get {
                return ResourceManager.GetString("exception_target_index_not_last", resourceCulture);
            }
        }
    }
}
